config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'what-is-storyhoot', to: 'static_pages#about', :as => :about
  get 'privacy', to: 'static_pages#privacy', :as => :privacy
  get 'terms', to: 'static_pages#terms', :as => :terms

  resources :users, path: '/u' do
    member do
      get :subscribers
      get :activate
    end
  end
  post 'users/change_password'
  post 'users/change_username'
  get 'feed', to: 'users#newsfeed'
  get 'find', to: 'users#find_authors', :as => :find_authors
  get 'complete-facebook-sign-up', to: 'users#complete_facebook_sign_up', :as => :complete_facebook_sign_up
  post 'users/verify_account'

  resources :sessions, only: [:create, :destroy]
  get 'login', to: 'sessions#new', :as => :login
  post 'logout', to: 'sessions#destroy', :as => :logout

  resources :password_resets
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :books, path: '/story/' do
    member do
      put "like", to: 'books#like'
      put "unlike", to: 'books#unlike'
    end
  end
  get 'gif-maker-pictures', to: 'books#gif_maker_pictures', :as => :gif_maker_pictures
  get 'gif-maker-video', to: 'books#gif_maker_video', :as => :gif_maker_video
  get 'gif-upload', to: 'books#gif_upload', :as => :gif_upload
  get 'discover', to: 'books#discover', :as => :discover

  resources :categories, only: [:index, :show]
  resources :subscriptions
  resources :comments, only: [:new, :create, :destroy]
  resources :hashtags, only: [:index]

  resources :bulletins, only: [:index]
  get 'notifications', to: 'bulletins#index'

  resources :support_tickets, only: [:new, :create]
  get 'contact', to: 'support_tickets#new', :as => :contact

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_filter :require_login

  layout 'plain'

  def home
    if current_user
      redirect_to feed_path
    else
      render :layout => 'splash'
    end
  end

  def about
  end

  def privacy
  end

  def terms
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="page-static-general">
  <header>

  </header>

  <section class="page-about text-center">
    <section class="section-header">
      <%= link_to image_tag('about-image-1.png', width: '500'), root_path %>
      <h2>Looks like you were curious to know what this was all about!</h2>
      <h3>Here's how it works..</h3>
    </section>
    <div class="row">
      <div class="large-4 medium-4 columns about-tip">
        <%= image_tag '2.png' %>
        <h4>Create a GIF</h4>
        <p>Use two or more photos or a video to create a GIF. You can also directly upload a GIF</p>
      </div>

      <div class="large-4 medium-4 columns about-tip">
        <%= image_tag '1.png' %>
        <h4>A profile page</h4>
        <p>Build a customised profile. Show off your GIFs on facebook and twitter</p>
      </div>

      <div class="large-4 medium-4 columns about-tip">
        <%= image_tag '3.png' %>
        <h4>Customised feed</h4>
        <p>Your home page is constructed from GIFs created by users you've subscribed to.</p>
      </div>
    </div>

    <%= link_to "Join Storyhoot now", new_user_path, class: 'ext-cta' unless current_user %>
  </section>
</div>

app/views/static_pages/home.html.erb
<h1>
  <%= image_tag "logo_storyhoot.png", alt: "Storyhoot" %>
</h1>

<h2>
  Share <strong>your story</strong> with the world.
</h2>

<%= link_to "Continue with Facebook", auth_at_provider_path(:provider => :facebook), class: 'splash-button ext-facebook' %>
<%= link_to "Sign up with email", new_user_path, class: 'splash-button ext-inverse' %>

<div class="splash-header">
  <div class="left">
    <%= link_to 'About', about_path %>
    <%= link_to 'Contact', contact_path %>
  </div>
  <div class="right">
    <%= link_to 'Log in', login_path %>
  </div>
</div>

<div class="splash-footer">
  <div class="left">
    <%= link_to 'Privacy', privacy_path %>
    <%= link_to 'Terms of use', terms_path %>
  </div>
</div>

app/views/static_pages/terms.html.erb
<div class="row">
  <div class="large-8 large-centered medium-10 medium-centered small-11 small-centered columns">
    <h3 class="text-center">TERMS OF USE</h3>
    <p>
        By accessing or using the Storyhoot website, the Storyhoot service, or any applications (including mobile applications) made available by Storyhoot
        (together, the "Service"), however accessed, you agree to be bound by these terms of use ("Terms of Use"). The Service is owned or controlled by Instagram,
        LLC ("Instagram").
        <strong>
            These Terms of Use affect your legal rights and obligations. If you do not agree to be bound by all of these Terms of Use, do not access or use the
            Service.
        </strong>
    </p>
    <p>
        There may be times when we offer a special feature that has its own terms and conditions that apply in addition to these Terms of Use. In those cases, the
        terms specific to the special feature control to the extent there is a conflict with these Terms of Use.
    </p>
    <p>
        <strong>
            ARBITRATION NOTICE: EXCEPT IF YOU OPT-OUT AND EXCEPT FOR CERTAIN TYPES OF DISPUTES DESCRIBED IN THE ARBITRATION SECTION BELOW, YOU AGREE THAT DISPUTES
            BETWEEN YOU AND STORYHOOT WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION AND YOU WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR
            CLASS-WIDE ARBITRATION.
        </strong>
    </p>
    <h2>
        Basic Terms
    </h2>
    <div>
        <ol>
            <li>
                You must be at least 13 years old to use the Service.
            </li>
            <li>
                You may not post violent, nude, partially nude, discriminatory, unlawful, infringing, hateful, pornographic or sexually suggestive images, GIFs or
                other content via the Service.
            </li>
            <li>
                You are responsible for any activity that occurs through your account and you agree you will not sell, transfer, license or assign your account,
                followers, username, or any account rights. With the exception of people or businesses that are expressly authorized to create accounts on behalf
                of their employers or clients, Instagram prohibits the creation of and you agree that you will not create an account for anyone other than
                yourself. You also represent that all information you provide or provided to Storyhoot upon registration and at all other times will be true,
                accurate, current and complete and you agree to update your information as necessary to maintain its truth and accuracy.
            </li>
            <li>
                You agree that you will not solicit, collect or use the login credentials of other Storyhoot users.
            </li>
            <li>
                You are responsible for keeping your password secret and secure.
            </li>
            <li>
                You must not defame, stalk, bully, abuse, harass, threaten, impersonate or intimidate people or entities and you must not post private or
                confidential information via the Service, including, without limitation, your or any other person's credit card information, social security or
                alternate national identity numbers, non-public phone numbers or non-public email addresses.
            </li>
            <li>
                You may not use the Service for any illegal or unauthorized purpose. You agree to comply with all laws, rules and regulations (for example,
                federal, state, local and provincial) applicable to your use of the Service and your Content (defined below), including but not limited to,
                copyright laws.
            </li>
            <li>
                You are solely responsible for your conduct and any data, text, files, information, usernames, images, graphics, photos, profiles, audio and video
                clips, sounds, musical works, works of authorship, applications, links and other content or materials (collectively, "Content") that you submit,
                post or display on or via the Service.
            </li>
            <li>
                You must not change, modify, adapt or alter the Service or change, modify or alter another website so as to falsely imply that it is associated
                with the Service or Storyhoot.
            </li>
            <li>
                You must not create or submit unwanted email, comments, likes or other forms of commercial or harassing communications (a/k/a "spam") to any
                Storyhoot users.
            </li>
            <li>
                You must not use domain names or web URLs in your username without prior written consent from Storyhoot.
            </li>
            <li>
                You must not interfere or disrupt the Service or servers or networks connected to the Service, including by transmitting any worms, viruses,
                spyware, malware or any other code of a destructive or disruptive nature. You may not inject content or code or otherwise alter or interfere with
                the way any Storyhoot page is rendered or displayed in a user's browser or device.
            </li>
            <li>
                You must not create accounts with the Service through unauthorized means, including but not limited to, by using an automated device, script, bot,
                spider, crawler or scraper.
            </li>
            <li>
                You must not attempt to restrict another user from using or enjoying the Service and you must not encourage or facilitate violations of these Terms
                of Use or any other Storyhoot terms.
            </li>
            <li>
                Violation of these Terms of Use may, in Storyhoot&#8217;s sole discretion, result in termination of your Storyhoot account. You understand and
                agree that Instagram cannot and will not be responsible for the Content posted on the Service and you use the Service at your own risk. If you
                violate the letter or spirit of these Terms of Use, or otherwise create risk or possible legal exposure for Storyhoot, we can stop providing all or
                part of the Service to you.
            </li>
        </ol>
    </div>
  </div>
</div>