config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'what-is-storyhoot', to: 'static_pages#about', :as => :about
  get 'privacy', to: 'static_pages#privacy', :as => :privacy
  get 'terms', to: 'static_pages#terms', :as => :terms

  resources :users, path: '/u' do
    member do
      get :subscribers
      get :activate
    end
  end
  post 'users/change_password'
  post 'users/change_username'
  get 'feed', to: 'users#newsfeed'
  get 'find', to: 'users#find_authors', :as => :find_authors
  get 'complete-facebook-sign-up', to: 'users#complete_facebook_sign_up', :as => :complete_facebook_sign_up
  post 'users/verify_account'

  resources :sessions, only: [:create, :destroy]
  get 'login', to: 'sessions#new', :as => :login
  post 'logout', to: 'sessions#destroy', :as => :logout

  resources :password_resets
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :books, path: '/story/' do
    member do
      put "like", to: 'books#like'
      put "unlike", to: 'books#unlike'
    end
  end
  get 'gif-maker-pictures', to: 'books#gif_maker_pictures', :as => :gif_maker_pictures
  get 'gif-maker-video', to: 'books#gif_maker_video', :as => :gif_maker_video
  get 'gif-upload', to: 'books#gif_upload', :as => :gif_upload
  get 'discover', to: 'books#discover', :as => :discover

  resources :categories, only: [:index, :show]
  resources :subscriptions
  resources :comments, only: [:new, :create, :destroy]
  resources :hashtags, only: [:index]

  resources :bulletins, only: [:index]
  get 'notifications', to: 'bulletins#index'

  resources :support_tickets, only: [:new, :create]
  get 'contact', to: 'support_tickets#new', :as => :contact

end

app/models/user.rb
class User < ActiveRecord::Base

  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications

  acts_as_reader
  acts_as_voter

  searchkick
  def self.text_search(query, page)
    if query.present?
      self.search query, boost_by: [:total_view_count], page: page, per_page: 6
    end
  end

  has_many :books, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bulletins, dependent: :destroy
  has_many :uploads, dependent: :destroy
  has_many :hashtags, dependent: :destroy

  has_many :subscriptions, :foreign_key => 'author_id'
  has_many :subscribers, through: :subscriptions

  has_many :reverse_subscriptions, :foreign_key => 'subscriber_id', :class_name => 'Subscription'
  has_many :authors, through: :reverse_subscriptions

  validates :username, uniqueness: { case_sensitive: false} , presence: true, format: { with: /\A[\w\-_.]*\z/i }
  validates :email, uniqueness: true, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }, if: :new_user?

  before_validation :prep_email
  before_save :prep_username

  has_attached_file :avatar,
		    :styles => {
		      :medium => "300x300#",
		      :thumb => "100x100#"
		    },
		    :default_url => "ProfilePic.png",
		    :convert_options => {
		      :all => "-interlace plane",
		      :medium => "-quality 85",
		      :thumb => "-quality 70"
		    }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_attached_file :cover,
		    :styles => {
		      :cover_size => "1300x440#",
		      :thumb => "100x100#"
		    },
		    :default_url => "CoverPic.png",
		    :convert_options => {
		      :all => "-interlace plane",
		      :cover_size => "-quality 85",
		      :thumb => "-quality 75"
		    }
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  def to_param
    "#{username}".parameterize
  end

  def subscribed?(other_user)
    self.reverse_subscriptions.find_by(author_id: other_user.id)
  end

  def subscribe!(other_user)
    self.reverse_subscriptions.create!(author_id: other_user.id, subscriber_id: self.id)
  end

  def unsubscribe!(other_user)
    self.reverse_subscriptions.find_by(author_id: other_user.id, subscriber_id: self.id).destroy
  end

  def feed
    Book.from_users_followed_by(self).order('created_at DESC')
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def send_verification_request
    admin_emails = ['prajwalpy6@gmail.com', 'kevinjolly7@hotmail.com']
    admin_emails.each do |email|
      AdminMailer.request_verification(self, email).deliver
    end
  end

  def update_user_total_view_count
    update(total_view_count: self.books.sum(:view_count))
  end

  private

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def prep_email
    self.email = self.email.strip.downcase if self.email
  end

  def prep_username
    self.username = self.username.strip.downcase if self.username
  end

  def new_user?
    new_record?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	skip_before_filter :require_login, only: [:new, :create, :activate]
	
	layout 'splash', :only => [:new, :create, :complete_facebook_sign_up]

	def index
		@users = User.text_search(params[:query], params[:page])
	end

	def new
		@user = User.new
		if logged_in?
			redirect_to feed_path
		end
	end

	def create
		@user = User.new(user_params)
		if @user.save
			auto_login @user
			redirect_to find_authors_path
			flash[:notice] = "A confirmation email has been sent to you. Please confirm your email to be able to post gifs."
		else
			render :new
		end
	end

	def show
		@user = User.find_by(username: params[:id])
		@books = @user.books.order('created_at DESC')
	end

	def edit
		@user = User.find_by(username: params[:id])
		if @user != current_user
			redirect_to current_user
			flash[:notice] = "Error in the request"
		end
	end

	def update
		@user = User.find_by(username: params[:id])
		if @user.update(user_params)
			redirect_to @user
			flash[:notice] = "Profile successfully updated"
		else
			render 'edit'
		end
	end

	def change_password
		user = current_user
		if User.authenticate(user.username, params[:current_password]) &&
			params[:new_password] == params[:confirm_password] &&
			params[:new_password].length >= 6
			user.update_attributes(password: params[:new_password])
			flash[:notice] = "Password change successful"
			redirect_to user
		else
			flash[:notice] = "Password change unsuccessful"
			redirect_to edit_user_path user
		end
	end

	def change_username
		user = current_user
		if user.update_attributes(username: params[:username])
			flash[:notice] = "You have logged in successfully from facebook"
			redirect_to find_authors_path
		else
			flash[:notice] = "Seems like the username already exists."
			redirect_to complete_facebook_sign_up_path
		end
	end

	def activate
		if @user = User.load_from_activation_token(params[:id])
		  @user.activate!
		  redirect_to login_path
		  flash[:notice] = 'Your account has been activated successfully. You can post gifs now.'
		else
		  not_authenticated
		end
	end

	def subscribers
		@user = User.find_by(username: params[:id])
		@subscribers = @user.subscribers
	end

	def feed
		Book.from_users_followed_by(self)
	end

	def newsfeed # this is the view
		@user_now = current_user
		@feed_items = @user_now.feed.paginate(:page => params[:page], :per_page => 5)
	  @comment = Comment.new
	  @users_to_follow = User.where.not(id: @user_now.author_ids).order('books_count DESC').limit(6)
	end

	def find_authors
		@authors = User.order('total_view_count DESC').limit(12)
	end

	def complete_facebook_sign_up
	end

	def verify_account
		user = current_user
		if !user.verification_request && user.update_attributes(verification_request: 'requested')
			user.send_verification_request
			flash[:notice] = "You have successfully requested an account verification."
			redirect_to current_user
		else
			flash[:notice] = "You have already requested a verification."
			redirect_to current_user
		end
	end

	private
			def user_params
				params.require(:user).permit(:username, :name, :email, :password, :cover, :avatar, :about_me, :authentications_attributes)
			end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/complete_facebook_sign_up.html.erb
<div class="row text-center" id="change-username-after-facebook-authentication">
  <p>
    Welcome to storyhoot!
    <br>
    It is recommended that you set a unique username now.
  </p>
  <div class="large-4 large-centered columns custom-form">

    <%= form_tag users_change_username_path do %>
      <%= text_field_tag :username, nil, placeholder: 'Choose a username.' %>
      <div class="text-center">
        <%= submit_tag 'Create my account', class: 'button tiny radius' %>
      </div>
    <% end %>

  </div>
</div>

app/views/users/edit.html.erb
<div class="row" id="user-edit-page">
	<div class="large-10 large-centered columns">
		<hr>
		<h3 class="text-center">User Settings</h3>
		<hr>
		<ul class="tabs" data-tab>
			<li class="tab-title active">
				<a href="#profile-settings">Profile Settings</a>
			</li>
			<li class="tab-title">
				<a href="#display-pic-settings">Display Pics</a>
			</li>
			<li class="tab-title">
				<a href="#change-password">Change Password</a>
			</li>
			<li class="tab-title">
				<a href="#verify-account">Verify Account</a>
			</li>
		</ul>
		<div class="tabs-content">
			<div class="content active" id="profile-settings">

				<%= form_for @user do |f| %>
						<% if @user.errors.any? %>
						  <div class="alert">
						    <p><%= pluralize(@user.errors.count, 'error') %></p>
						    <ul class="no-bullet">
						      <% @user.errors.full_messages.each do |msg| %>
						        <li><%= msg %></li>
						      <% end %>
						    </ul>
						  </div>
						<% end %>

						<div class="row">
							<div class="large-10 large-centered columns">
								<label>Username
									<%= f.text_field :username, placeholder: 'Username' %>
								</label>
							</div>
						</div>

						<div class="row">
							<div class="large-10 large-centered columns">
								<label>Name
									<%= f.text_field :name, placeholder: 'Name' %>
								</label>
							</div>
						</div>

						<div class="row">
							<div class="large-10 large-centered columns">
								<label>Email
									<%= f.email_field :email, placeholder: 'Email' %>
								</label>
							</div>
						</div>

						<div class="row">
							<div class="large-10 large-centered columns">
								<label>About Me
									<%= f.text_area :about_me, placeholder: 'About me' %>
								</label>
							</div>
						</div>

						<div class="text-center">
						  <%= f.submit 'Save Changes', class: 'button tiny radius' %>
						</div>

				<% end %>

			</div>
			<div class="content" id="display-pic-settings">
				
			<%= form_for @user, htnl: {multipart: true} do |f| %>
						<% if @user.errors.any? %>
						  <div class="alert">
						    <p><%= pluralize(@user.errors.count, 'error') %></p>
						    <ul>
						      <% @user.errors.full_messages.each do |msg| %>
						        <li><%= msg %></li>
						      <% end %>
						    </ul>
						  </div>
						<% end %>

						<div class="row">
							<div class="large-6 columns">
								<div class="row">
									<div class="large-6 large-centered columns">
										<%= image_tag @user.avatar.url(:thumb), class: 'rounded-image-with-border' %>
										<label>Change profile picture
											<%= f.file_field :avatar %>
										</label>
									</div>
								</div>
							</div>

							<div class="large-6 columns">
								<div class="row">
									<div class="large-6 large-centered columns">
										<%= image_tag @user.cover.url(:thumb), class: 'rounded-image-with-border predefined-height-100' %>
										<label>Change cover picture
											<%= f.file_field :cover %>
										</label>
									</div>
								</div>
							</div>
						</div>

						<div class="text-center">
						  <%= f.submit 'Save Changes', class: 'button tiny radius' %>
						</div>

				<% end %>

			</div>
			<div class="content" id="change-password">
				
				<div class="row">
					<div class="large-10 large-centered columns">
						<%= form_tag users_change_password_path do %>
							<%= password_field_tag :current_password, nil, placeholder: 'Current Password' %>
							<%= password_field_tag :new_password, nil, placeholder: 'New Password' %>
							<%= password_field_tag :confirm_password, nil, placeholder: 'Confirm Password' %>
							<div class="text-center">
								<%= submit_tag 'Change Password', class: 'button tiny radius' %>
							</div>
						<% end %>
					</div>
				</div>

			</div>
			<div class="content" id="verify-account">

				<div class="row text-center">
					<% if @user.verified_status == 'verified' %>
						<p>You are verified</p>
					<% else %>
						<%= link_to 'Request account verfication', users_verify_account_path, method: 'post', class: 'button radius' %>
					<% end %>
				</div>

			</div>
		</div>
	</div>
</div>

app/views/users/find_authors.html.erb
<div class="row">
  <div class="large-12 columns" id="welcome-div">
    <div class="text-center" id="welcome-div-top-part">
      <h2>Welcome to Storyhoot</h2>
      <h5 class="subheader">
        “Hello there, <%= current_user.name %> ! Storyhoot is a fun and fast way to create and share gifs with the world”
      </h5>
      <%= link_to 'Skip this and Proceed to profile', current_user, class: 'button tiny' %>
      <h5 class="subheader">
        Follow 5 users, then we’ll build a custom home feed for you”
      </h5>
    </div>
    <div class="row" id="find-authors-container">
      <% @authors.each do |author| %>
        <% if author != current_user %>
          <%= render 'shared/user', user: author %>
        <% end %>
      <% end %>
    </div>
    <div class="text-center">
      <%= link_to "I'm done. Take me to my feed", feed_path, class: 'button tiny' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
	<div class="large-10 large-centered columns" id="search-results-users">
		<p class="text-center">
			Displaying users that match 
			<span class="pattern">
				<%= params[:query] %>
			</span>
		</p>
		<% if @users.any? %>
			<div class="row">
				<%= render partial: 'shared/user', collection: @users %>
			</div>
		<% else %>
			<h5 class="text-center"><br>Sorry. We couldn't find matches for your search query</h5>
		<% end %>
	</div>
</div>

<div class="text-center">
	<p>
		<%= will_paginate @users %>
	</p>
</div>

app/views/users/index.js.erb
$('#search-results-users').append('<%= escape_javascript( render partial: 'shared/user', collection: @users ) %>');
<% if @users.next_page %>
  $('.pagination').replaceWith('<%= escape_javascript( will_paginate(@users) ) %>');
<% else %>
  $('.pagination').text('No more users to show');
<% end %>
<% sleep 1 %>

app/views/users/likers.html.erb
<% if @likers.any? %>
<div class="row">
	<div class="large-11 large-centered columns">
		<div class="row">
			<div class="large-4 columns">
				<div class="book_container">
					<% @likers.each do |f|%>
						<%= link_to image_tag(f.avatar.url(:medium), size: '200x200'), user_path(f.username) %>
						<h4><%= f.name %><small> @ <%= f.username %></small></h4>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>
<% else %>
<h4> No Likes yet </h4>
<% end %>

app/views/users/new.html.erb
<div class="row">
	<div class="large-4 columns large-centered custom-form">
    <div class="text-center">
      <%= link_to image_tag('logo_storyhoot.png'), root_path %>
    </div>
		<%= render 'shared/sign_up' %>
    <p class="text-center">
      Have an account already?
      <br>
      <%= link_to 'Sign in here.', login_path %>
    </p>
	</div>
</div>

app/views/users/newsfeed.html.erb
<div class="row collapse">
  <div class="large-9 medium-9 small-12 columns">

    <div class="row collapse" id="feed-content">
      <% if @feed_items.any? %>
        <%= render partial: 'shared/feed_item', collection: @feed_items %>
      <% end %>
    </div>
    <div class="large-8 large-offset-4 medium-8 medium-offset-4 columns text-center">
      <%= will_paginate @feed_items %>
    </div>

  </div>
  <div class="large-3 medium-3 columns show-for-medium-up">

    <div id="sidebar-on-feed" class="text-center">
      <div id="user-images-container-on-feed">
        <%= image_tag current_user.cover.url(:cover_size), id: 'user-cover-pic' %>
        <%= image_tag current_user.avatar.url(:medium), id: 'user-profile-pic' %>
      </div>
      <h4>
        <%= current_user.name %>
        <small> @<%= current_user.username %></small>
        <br>
        <em><small><b><%= current_user.about_me.truncate(50) if current_user.about_me %></b></small></em>
      </h4>

      <div id="user-stats-container-on-feed">
        <p>
          <%= pluralize current_user.subscribers.count, 'subscriber' %>
          &nbsp;
          <%= pluralize current_user.books.count, 'gif' %>
          &nbsp;
          <%= pluralize current_user.total_view_count, 'view' %>
        </p>
      </div>

      <div class="row" id="who-to-follow">

        <h4>Who to follow</h4>

        <% @users_to_follow.each do |user| %>
          <% if user != current_user %>
            <%= render 'shared/user', user: user %>
          <% end %>
        <% end %>

      </div>
    </div>

  </div>
</div>

app/views/users/newsfeed.js.erb
$('#feed-content').append('<%= escape_javascript( render(partial: 'shared/feed_item', collection: @feed_items) ) %>');
<% if @feed_items.next_page %>
  $('.pagination').replaceWith('<%= escape_javascript( will_paginate(@feed_items) ) %>');
<% else %>
  $('.pagination').text('No more stories to show');
<% end %>
<% sleep 1 %>

app/views/users/show.html.erb
<div class="row collapse" id="profile-page">

	<div class="large-12 small-10 small-centered columns" id="user-images-container">
		<% if current_user == @user %>
			<%= link_to image_tag(@user.cover.url(:cover_size), id: 'user-cover-pic'), edit_user_path(current_user.username) %>
			<%= link_to image_tag(@user.avatar.url(:medium), id: 'user-profile-pic', class: 'rounded-image-with-border'), edit_user_path(current_user.username) %>
		<% else %>
			<%= image_tag @user.cover.url(:cover_size), id: 'user-cover-pic' %>
			<%= image_tag @user.avatar.url(:medium), id: 'user-profile-pic', class: 'rounded-image-with-border' %>
		<% end %>
	</div>

	<div class="large-12 small-10 small-centered columns" id="user-details-container">
		<div class="clearfix">
			<div class="left">
				<h3>
					<%= @user.name %>
					<small>
						@<%= @user.username %>
						<% if @user.verified_status == 'verified' %>
						  <i class="fi fi-check"></i>
						<% end %>
					</small>
					<br>
					<em><small><b><%= @user.about_me.truncate(50) if @user.about_me %></b></small></em>
				</h3>
				<p class="text-center">
					<span id="author-<%= @user.id %>-subscription-count">
						<%= link_to subscribers_user_path(@user.username), class: 'link-in-a-box' do %>
							<%= pluralize @user.subscribers.count, 'subscriber' %>
						<% end %>
					</span>
					&nbsp;
					<%= pluralize @user.books.count, 'gif' %>
					&nbsp;
					<%= pluralize @user.total_view_count, 'view' %>
				</p>
			</div>
			<div class="right" id="subscribe_div">
				<% if current_user != @user %>
					<div id="author-<%= @user.id %>-subscribe-div">
					<% if current_user.subscribed? @user %>
						<%= render 'shared/unfollow_form', auth: @user %>
					<% else %>
						<%= render 'shared/follow_form', auth: @user %>
					<% end %>
					</div>
				<% else %>
					<%= link_to 'Create new gif', new_book_path, class: 'button tiny radius' %>
				<% end %>
			</div>
		</div>
	</div>

	<div class="large-12 small-11 small-centered columns" id="user-books-container">
		<% if @books.any? %>

			<% @books.each do |book| %>
				<div class="large-2 medium-3 small-6 columns end">
					<%= div_for book do %>
						<div class="book-container">
							<%= link_to image_tag(book.cover.url(:thumb)), book %>
							<div class="clearfix options-profile">
									<div class="left likes-container" id="book-<%= book.id %>-likes">
										<% if current_user.voted_as_when_voted_for book %>
											<%= render 'shared/unlike_link', book: book %>
										<% else %>
											<%= render 'shared/like_link', book: book %>
										<% end %>
									</div>
									<div class="right">
										<i class="fi-eye large"></i> <%= book.impressionist_count %>
									</div>
							</div>
							<p class="title">
								<%= link_to book.title.truncate(20), book %>
							</p>
							<p class="time">
									created <%= time_ago_in_words(book.created_at) %> ago
							</p>
							<div class="clearfix">
								<div class="left">
									<% if current_user == @user %>
										<%= link_to book, :method => :delete do %>
											<span><i class="fi fi-x"></i> Delete</span>
										<% end %>
									<% end %>
								</div>
							</div>
						</div>
					<% end %>
				</div>
			<% end %>

		<% else %>

			<p class="text-center">
				<%= @user.username.capitalize %> hasn't published any gif yet.
			</p>

		<% end %>
	</div>
</div>

app/views/users/subscribers.html.erb
<% if @subscribers.any? %>
	<div class="row panel">
		<% @subscribers.each do |subscriber| %>
      <div class="large-3 columns end text-center">
        <%= link_to image_tag(subscriber.avatar.url(:thumb)), subscriber %>
        <p>
          <%= link_to subscriber.username, subscriber %>
        </p>
      </div>
    <% end %>
	</div>
	<% else %>
		<h4 class="text-center"><%= @user.username %> has no subscribers yet</h4>
	<% end %>