config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'what-is-storyhoot', to: 'static_pages#about', :as => :about
  get 'privacy', to: 'static_pages#privacy', :as => :privacy
  get 'terms', to: 'static_pages#terms', :as => :terms

  resources :users, path: '/u' do
    member do
      get :subscribers
      get :activate
    end
  end
  post 'users/change_password'
  post 'users/change_username'
  get 'feed', to: 'users#newsfeed'
  get 'find', to: 'users#find_authors', :as => :find_authors
  get 'complete-facebook-sign-up', to: 'users#complete_facebook_sign_up', :as => :complete_facebook_sign_up
  post 'users/verify_account'

  resources :sessions, only: [:create, :destroy]
  get 'login', to: 'sessions#new', :as => :login
  post 'logout', to: 'sessions#destroy', :as => :logout

  resources :password_resets
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :books, path: '/story/' do
    member do
      put "like", to: 'books#like'
      put "unlike", to: 'books#unlike'
    end
  end
  get 'gif-maker-pictures', to: 'books#gif_maker_pictures', :as => :gif_maker_pictures
  get 'gif-maker-video', to: 'books#gif_maker_video', :as => :gif_maker_video
  get 'gif-upload', to: 'books#gif_upload', :as => :gif_upload
  get 'discover', to: 'books#discover', :as => :discover

  resources :categories, only: [:index, :show]
  resources :subscriptions
  resources :comments, only: [:new, :create, :destroy]
  resources :hashtags, only: [:index]

  resources :bulletins, only: [:index]
  get 'notifications', to: 'bulletins#index'

  resources :support_tickets, only: [:new, :create]
  get 'contact', to: 'support_tickets#new', :as => :contact

end

app/views/shared/_bottom_navbar.html.erb
<div class="space-compensation-for-bottom-navbar"></div>

<div class="bottom-navbar">
  <nav>
    <ul>
    
      <li>
        <%= link_to feed_path do %>
          <%= image_tag 'home.png' %>
        <% end %>
      </li>

      <li>
        <%= link_to discover_path do %>
          <%= image_tag 'discover.png' %>
        <% end %>
      </li>

      <li id="create-gif">
        <%= link_to new_book_path do %>
          <%= image_tag 'new_gif.png' %>
        <% end %>
      </li>
      
      <li
        <% if current_user.bulletins.unread_by(current_user).count > 0 %>
          id="unread"
        <% end %>
      >
        <%= link_to notifications_path do %>
          <%= image_tag 'notifications.png' %>
        <% end %>
      </li>

      <li>
        <%= link_to user_path(current_user) do %>
          <%= image_tag 'profile.png' %>
        <% end %>
      </li>

    </ul>
  </nav>
</div>

app/views/shared/_bulletin.html.erb
<% @bulletins.each do |bulletin| %>
  <div class="panel radius">
    <div class="row">
      <div class="large-2 columns">
        <%= image_tag User.find(bulletin.notifier).avatar.url(:thumb), width: '50' %>
      </div>
      <div class="large-10 columns">
        <p>
          <%= link_to bulletin.content, bulletin.url %>
          <span class="time_ago"><%= time_ago_in_words(bulletin.created_at) %> ago</span>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_bulletin_unread.html.erb
<% @bulletins_unread.each do |bulletin| %>
  <div class="panel radius">
    <div class="row">
      <div class="large-2 columns">
        <%= image_tag User.find(bulletin.notifier).avatar.url(:thumb), width: '50' %>
      </div>
      <div class="large-10 columns">
        <p>
          <%= link_to bulletin.content, bulletin.url %>
          <span class="time_ago"><%= time_ago_in_words(bulletin.created_at) %> ago</span>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_create_book_form.html.erb
<h3 class="text-center">Create a new story</h3>
<%= form_for Book.new, :html => {:multipart => true} do |f| %>
	<%= f.text_field :title, placeholder: 'Write a title for your story in about 20 words' %>
	<%= f.text_area :description, placeholder: 'Write a description for your story in about 100 words', rows: 6 %>
  <%= f.select :category_id, Category.all.collect {|c| [ c.name, c.id ]} , prompt: "Select a Category" %>
  <%= f.label 'Upload a cover for your story' %>
  <%= f.file_field :cover %>
  <div class="text-center">
	  <%= f.submit 'Create story', class: 'button tiny radius' %>
  </div>
<% end %>

app/views/shared/_feed_item.html.erb
<div class="row feed-item">
	<div class="large-4 medium-4 small-12 columns">
		<div class="row">
			<div class="large-7 medium-12 small-9 columns text-right">
				<p>
					<span class="username"><%= link_to "@#{feed_item.user.username}", feed_item.user %></span>
					<br>
					<span class="time"><%= time_ago_in_words(feed_item.created_at) %> ago</span>
				</p>
			</div>
			<div class="large-5 medium-6 small-3 columns">
				<%= link_to image_tag(feed_item.user.avatar.url(:thumb)), feed_item.user %>
			</div>
		</div>
	</div>
	<div class="large-8 medium-8 columns gif-container">
		<div class="square">
			<div class="content">
				<div class="table">
					<div class="table-cell">
						<%= link_to image_tag(feed_item.cover.url), feed_item %>
					</div>
				</div>
			</div>
		</div>
		<div class="options-container text-right">
			<div class="option likes-container" id="book-<%= feed_item.id %>-likes">
				<% if current_user.voted_as_when_voted_for feed_item %>
					<%= render 'shared/unlike_link', book: feed_item %>
				<% else %>
					<%= render 'shared/like_link', book: feed_item %>
				<% end %>
			</div>
			<div class="option">
				<i class="fi-eye large"></i> <%= feed_item.impressionist_count %>
			</div>
			<div class="option">
				<a href="" class="share-button"><i class="fi-share"></i></a>
			</div>
			<div class="option social-buttons">
				<%= social_share_button_tag(
					feed_item.title,
					via: "storyhoot",
					url: "http://storyhoot.com/story/#{feed_item.id}",
					image: "#{asset_path feed_item.cover.url(:medium)}",
					desc: "Share your story with the world"
					)
				%>
			</div>
		</div>
		<div class="clearfix">
			<p class="feed-title">
					<%= auto_link(feed_item.title).html_safe %>
			</p>
		</div>
		
		<% if feed_item.comments.any? %>
			<p class="comments-count">
				<%= link_to "#{feed_item.comments.count} #{'comment'.pluralize(feed_item.comments.count)}", book_path(feed_item.id) %>
			</p>
			<div class="comments-section <%= 'comments-section-fixed-height' if (feed_item.comments.count > 3) %>">
				<% feed_item.comments.each do |comment| %>
					<div class="row collapse">
						<div class="large-1 small-2 columns">
							<%= link_to image_tag(comment.user.avatar.url(:thumb)), user_path(comment.user.username) %>
						</div>
						<div class="large-11 small-10 columns">
							<p>
								<span class="comments-username">
									<%= link_to comment.user.username, user_path(comment.user.username) %>
								</span>
								<span class="comment-content">
									<%= auto_link(comment.content).html_safe %>
								</span>
							</p>
						</div>
					</div>
				<% end %>
			</div>
		<% end %>
		<br>
		<div class="comment_box">
			<%= form_for(@comment) do |f| %>
				<%= f.text_field :content, placeholder: 'Comment...' %>
				<%= f.hidden_field :book_id, value: feed_item.id %>
			<% end %>
		</div>
	</div>
	<div class="large-3 columns">
	</div>
</div>

app/views/shared/_follow_form.html.erb
<%= form_for current_user.reverse_subscriptions.build(author_id: auth.id), remote: true do |f| %>
	<%= f.hidden_field :author_id %>
	<%= f.submit 'Subscribe', class: 'button radius tiny' %>
<% end %>

app/views/shared/_hashtag.html.erb
<div class="row hashtag-container">
  <% if hashtag.hashtag_type == 'book_title' %>
    <div class="large-4 medium-4 small-4 columns">
      <%= link_to image_tag(hashtag.book.cover.url, class: 'image-with-curved-edges'), hashtag.book %>
    </div>
    <div class="large-8 medium-8 small-8 columns">
      <h2>
        <%= auto_link(hashtag.content).html_safe %>
      </h2>
      <p>
        by <%= link_to hashtag.user.username, user_path(hashtag.user.username) %>
      </p>
    </div>
  <% elsif hashtag.hashtag_type == 'comment_content' %>
    <div class="large-9 medium-9 small-8 columns">
      <h2>
        <%= auto_link(hashtag.content).html_safe %>
      </h2>
      <p>
        comment by <%= link_to hashtag.user.username, user_path(hashtag.user.username) %> on <%= link_to hashtag.book.title, hashtag.book %>
      </p>
    </div>
    <div class="large-3 medium-3 small-4 columns">
      <%= link_to image_tag(hashtag.book.cover.url, class: 'image-with-curved-edges'), hashtag.book %>
    </div>
  <% end %>
</div>

app/views/shared/_login_form.html.erb
<h3 class="text-center">Log in with email</h3>
<%= form_tag sessions_path, :method => :post do %>
	<%= text_field_tag :username_or_email, nil, placeholder: "Username or Email" %>
	<%= password_field_tag :password, nil,  placeholder: "Password" %>
  <!--
  <div class="text-left">
    <%= check_box_tag :remember_me, class: 'left' %>
    <%= label_tag :remember_me, 'Remember me' %>
  </div>
  -->
  <div class="text-right">
	  <%= submit_tag "Log In", class: 'button tiny' %>
  </div>
<% end %>

<div class="text-center" id="external-account-login-container">
  <%= link_to auth_at_provider_path(:provider => :facebook) do %>
    <span>
      You can also connect with
      <br>
      <i class="fi-social-facebook"></i>
    </span>
  <% end %>
</div>

<br>

app/views/shared/_navbar.html.erb
<div class="row-collpase" id="custom-navbar">

  <div class="large-2 columns">
    <%= link_to(image_tag('storyhoot-logo-white.png', class: 'brand'), feed_path) %>
  </div>

  <div class="large-8 columns">
    <%= form_tag books_path, :method => :get do %>
    <div class="row collapse">
      <div class="large-11 small-9 columns">
        <%= text_field_tag :query, params[:query], :placeholder => 'Search for cool gifs' %>
      </div>
      <div class="large-1 small-3 columns">
        <%= link_to '#' do %>
          <span id="categories-trigger">
            <i class="fi-list"></i>
          </span>
        <% end %>
        <div class = "row" id="categories-container">
          <% categories.each do |category| %>
            <div class="large-6 columns">
              <%= link_to category.name, category %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="large-2 columns">
    <div id="navbar-user-details" class="row collapse">
      <div class="small-2 columns">
        <%= link_to image_tag(current_user.avatar.url(:thumb), class: 'profile-pic'), user_path(current_user.username) %>
      </div>
      <div class="small-8 columns">
        <%= link_to current_user.username, user_path(current_user.username), id: 'user-menu-trigger' %>

        <div id="user-options-for-custom-navbar">
          <ul>
            <li>
              <%= link_to 'Create GIF', new_book_path, class: 'button' %>
            </li>
            <li>
              <%= link_to 'Discover', discover_path %>
            </li>
            <li>
              <%= link_to 'View Profile', user_path(current_user.username) %>
            </li>
            <li>
              <%= link_to notifications_path do %>
                <span>
                  Notifications
                </span>
                <span id ="notification-count">
                  <%= current_user.bulletins.unread_by(current_user).count %> unread
                </span>
              <% end %>
            </li>
            <li>
              <%= link_to 'Settings', edit_user_path(current_user.username) %>
            </li>
            <li>
              <% if @user && !@user.verified_status == 'verified' %>
                <%= link_to 'Verify Account', users_verify_account_path, method: 'post' %>
              <% end %>
            </li>
            <li>
              <%= link_to 'Logout', :logout, method: :post %>
            </li>
          </ul>
        </div>

      </div>  
      <div class="small-2 columns">
      </div>
    </div>
  </div>
</div>

<div style="height: 50px"></div>

app/views/shared/_navbar_splash.html.erb
<section id="splash-page-navbar">
  <div class="clearfix">
    <div class="left">
      <%= link_to image_tag('brand.jpg', class: 'logo'), '#' %>
    </div>
    <div class="right">
      <%= link_to image_tag('b.jpg', class: 'logo'), '#' %>
    </div>
  </div>
</section>

app/views/shared/_notices.html.erb
<% if flash[:notice] %>
  <div class="text-center notice">
    <div class="right">
      <a class="close-notice">
        <span><i class="fi fi-x"></i></span>
      </a>
    </div>
    <p>
      <%= flash[:notice] %>
    </p>
  </div>
<% end %>

app/views/shared/_sign_up.html.erb
<h3 class="text-center">Sign up with email</h3>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="alert text-left">
      <ul class="no-bullet">
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.text_field :username, placeholder: 'Username', pattern: '[\w\-_.]*', title: 'Special characters allowed . - _' %>
  <%= f.text_field :name, placeholder: 'Name' %>
  <%= f.email_field :email, placeholder: 'Email' %>
  <%= f.password_field :password, placeholder: 'Password' %>
  <div class="text-right">
    <%= f.submit 'Sign up', class: 'button tiny' %>
  </div>
<% end %>
<p class="text-center">
  By signing up, I accept Storyhoot's 
  <%= link_to 'terms of use', '#' %> and
  <%= link_to 'privacy policy.', '#' %>
</p>

<div class="text-center" id="external-account-login-container">
  <%= link_to auth_at_provider_path(:provider => :facebook) do %>
    <span>
      You can also connect with
      <br>
      <i class="fi-social-facebook"></i>
    </span>
  <% end %>
</div>

<br>

app/views/shared/_unfollow_form.html.erb
<%= form_for current_user.reverse_subscriptions.find_by(author_id: auth.id), :html => {method: :delete}, remote: true do |f| %>
	<%= f.submit "Unsubscribe", class: 'button radius tiny' %>
<% end %>

app/views/shared/_user.html.erb
<div class="large-4 medium-4 small-6 columns text-center end">
  <%= link_to image_tag(user.avatar.url(:medium), class: 'image-with-curved-edges'), user_path(user.username) %>
  <h5 class="text-center">
    <%= link_to user_path(user.username) do %>
      <span><%= user.username %>
      <% if user.verified_status == 'verified' %>
        <i class="fi fi-check"></i>
      <% end %>
      </span>
    <% end %>
  </h5>
  <p class="details">
    <%= user.total_view_count %> views
    <span id="author-<%= user.id %>-subscription-count">
      <%= link_to("#{user.subscriptions.count} subscribers", subscribers_user_path(user)) %>
    </span>
  </p>
  <% if current_user != user %>
    <div id="author-<%= user.id %>-subscribe-div">
      <% if current_user.subscribed? user %>
        <%= render 'shared/unfollow_form', auth: user %>
      <% else %>
        <%= render 'shared/follow_form', auth: user %>
      <% end %>
    </div>
  <% end %>
</div>